### ISSUE TITLE
It has a auto download all? 

### ISSUE THREAD

**Issue by Sirfrancis17** [xorilog/docker-telegram#10]
Hello
More than a mistake is a question
I want to configure this on a Linux server. My goal is to configure the client to automatically download all files that have been 
Is this possible? 
Thank you

**Comment by xorilog** [comment]
Hello @Sirfrancis17 docker-telegram provides you the Desktop version of the client with the GUI. In order to do what you want i guess the following project https://github.com/vysheng/tg will suit your needs better !
Have a nice day !
