### ISSUE TITLE
New tools 😊

### ISSUE THREAD

**Issue by temporallyaccount** [xorilog/docker-telegram#17]
1. https://element.io/
https://github.com/vector-im/element-desktop
2. https://wire.com/
https://github.com/wireapp/wire-desktop
3. https://jami.net/
https://git.jami.net/savoirfairelinux/ring-project

If proper docker files exist, let me know otherwise

**Comment by xorilog** [comment]
Hello what is the point of your issue ?

**Comment by temporallyaccount** [comment]
Sometimes i use your images with x11docker. You already have made for telegram, slack, discord then few other suggestions.

About problems, your telegram image misses fonts that help to display other languages (Cons: Unable to view other languages channels, group contents etc) then currently only display english language contents and rest as rectangle symbols and it seems also doesn't support for other input methods except english.

**Comment by kovetskiy** [comment]
I believe the fonts issue can be solved by mounting /usr/share/fonts. I don't have such issues with fonts though.

**Comment by xorilog** [comment]
@temporallyaccount do you aggree with the solution provided by @kovetskiy ? If it does work well for you then, i can add something in that direction, but i'm not planning to include all fonts available in the image.

On the suggestions you made, i do not plan to do this kind of dockerization for other software at present time.

**Comment by xorilog** [comment]
Closing without response.
