### ISSUE TITLE
Retrieve latest Telegram version during build

### ISSUE THREAD

**Issue by findesgh** [xorilog/docker-telegram#22]
Wouldn't it make more sense to retrieve the latest version number of telegram during build, i.e. in the Dockerfile, instead of the update script? I prefer to build the container locally and this would make things much more convenient for me. Maybe I'm missing a good argument against it though?

**Comment by xorilog** [comment]
We'll it is perfectly doable but it is more convenient for me as that script creates a tag in the repository. Which cannot be done at build time.
But this script can evolve as well as the dockerfile to ease local build.

**Comment by findesgh** [comment]
I see, that makes sense, of course. I'll see if I can come up with something that satisfies both requirements.

**Comment by findesgh** [comment]
I've solved this for myself by adding some very simple argument handling to the update script with a `-bo`/`--build-only` option, which limits what the script does to the local build. Default behavior is as now. Happy to create a PR if you believe this could be useful, but be warned: it's not very sophisticated :-).

**Comment by findesgh** [comment]
Otherwise feel free to close ;-).

**Comment by xorilog** [comment]
after some time, you finally get what you wanted ! i hope it fit your need well :)
