### ISSUE TITLE
Container not created ( libgtk-3.so.0: cannot open shared object file: No such file or directory )

### ISSUE THREAD

**Issue by trinityzhub** [xorilog/docker-telegram#23]
**ERROR:
"libgtk-3.so.0: cannot open shared object file: No such file or directory"**

Container not created. Could you suggest any solution?

exited with the below error in the terminal : 

> QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
> libgtk-3.so.0: cannot open shared object file: No such file or directory

Telegram Log :

> 
> org.telegram.desktop._fe7ffeda496e8935ac5c344c99863f04.desktop
> [2023.01.25 16:49:20] QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-user'
> [2023.01.25 16:49:20] Connecting local socket to /tmp/6ce7de587ddacca886605fc2d7c74451-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
> [2023.01.25 16:49:20] This is the only instance of Telegram, starting server and app...
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
> [2023.01.25 16:49:21] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'

**NOTE:**

OS Info `cat /etc/os-release` : 

> PRETTY_NAME="Debian GNU/Linux 10 (buster)"
> NAME="Debian GNU/Linux"

 Linux kernel version  `uname -r` : 

> 5.10.0-0.bpo.8-amd64

Architecture info `uname -m`  :

> x86_64

**Already tried :** 

- [x] `sudo apt install libgtk-3-0
- [x] Created/Build an image using  `FROM debian:buster-slim as downloader`  successfully. But Facing same issue while creating container

`

**Comment by trinityzhub** [comment]
**Could you share the build command so I change os and try to fix the architecture issue, I hope it might be the reason for the issue   **

`docker build -t "local-build/telegram:latest"` not working for me

**Comment by xorilog** [comment]
Hello !

`libgtk-3-0` can indeed be added to the container to remove that error, however it is not blocking and even without it i do get the UI poping.

can you please verify that the `<Your_storage_dir>` is correctly replaced by a directory you choose to use, as well as having the right rights ?
You may as well run it with your user and group using the following parrameters to the docker run command `-u $(id -u):$(id -g)`

here is an example:
- for a user named `trinityzhub` ( which must be the output of the command  `whoami` )
- with a home path `/home/trinityzhub`  ( which must be the the output of `echo $HOME` )
- storing it's configuration under `/home/trinityzhub/.config/.TelegramDesktop`.

First, you must create and ensure that your user have the directory holding your configuration:
```bash
mkdir -p ${HOME}/.config/.TelegramDesktop
```

then launch the following command:

```bash
docker run --rm -it --name telegram \
       --hostname=$(hostname) -u $(id -u):$(id -g) \
       -e DISPLAY=unix$DISPLAY \
       -e PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v "/home/$(whoami)/.Xauthority:/home/user/.Xauthority" \
       -v $XDG_RUNTIME_DIR/pulse:$XDG_RUNTIME_DIR/pulse \
       -v /etc/localtime:/etc/localtime:ro \
       -v ${HOME}/.config/.TelegramDesktop:/home/user/.local/share/TelegramDesktop/ \
       xorilog/telegram:v4.5.3
```

I will add the `libgtk-3-0` to the Built image however to avoid an unnecessary error message in an upcomming version.

**Comment by xorilog** [comment]
The main issue reported (as title) is now handled, i leave this Issue open if your issue (which shall be different from gtk3) is not resolved.

**Comment by trinityzhub** [comment]
- [ ] Tried to run:
```
docker pull xorilog/telegram:4.5.3


docker run --rm -it --name telegram \
       --hostname=$(hostname) -u $(id -u):$(id -g) \
       -e DISPLAY=unix$DISPLAY \
       -e PULSE_SERVER=unix:$XDG_RUNTIME_DIR/pulse/native \
       -v /tmp/.X11-unix:/tmp/.X11-unix \
       -v "/home/$(whoami)/.Xauthority:/home/user/.Xauthority" \
       -v $XDG_RUNTIME_DIR/pulse:$XDG_RUNTIME_DIR/pulse \
       -v /etc/localtime:/etc/localtime:ro \
       -v ${HOME}/.config/.TelegramDesktop:/home/user/.local/share/TelegramDesktop/ \
       xorilog/telegram:4.5.3
```

But facing some issues to run:

> No protocol specified
> qt.qpa.xcb: could not connect to display unix:0
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.


(Sorry for the delay)

**Comment by trinityzhub** [comment]
Thanks

**Comment by xorilog** [comment]
> Thanks

Is your issue now solved ? may i close this ticket ?

**Comment by xorilog** [comment]
Closing due to lack of response.
