### ISSUE TITLE
File sharing

### ISSUE THREAD

**Issue by Enelar** [xorilog/docker-telegram#6]
Im new to docker, could you please give me a hint, how to mount local home folder in rw mode into docker image, so it would actually able to save files and upload. Thank a lot for great receipt!

**Comment by xorilog** [comment]
Hello sorry to reply you that late, i missed the notification...
In order to mount a volume you can use the '-v' parameter like the following:
```
-v ~/.contained/.TelegramDesktop:/root/.local/share/TelegramDesktop/
```
This will mount your local directory ~/.contained/.TelegramDesktop as /root/.local/share/TelegramDesktop/ in the container.
Regards !
