### ISSUE TITLE
Dockerfile/update.sh: wget is broken

### ISSUE THREAD

**Issue by alyxazon** [xorilog/docker-telegram#7]
Hi,

The download location "https://tdesktop.com/linux/tsetup.1.4.3.tar.xz" does not exist anymore.

You can get it from here now: https://updates.tdesktop.com/tlinux/tsetup.1.4.3.tar.xz

Cheers

**Comment by xorilog** [comment]
Hi, 

Thank's the urls have changed, i just fixed them and updated.
ref: https://github.com/xorilog/docker-telegram/commit/9429c9ae741a208226d2fe0a595e39166103fcf7

Cheers !
