### ISSUE TITLE
no sound

### ISSUE THREAD

**Issue by ezbik** [xorilog/docker-telegram#9]
Hi, I got it fixed ( no sound when playing voice messages) :

```
diff --git a/Dockerfile b/Dockerfile
index 42ef77d..b0b1777 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -36,6 +36,7 @@ RUN apt-get update && apt-get install -y \
     software-properties-common \
     libx11-xcb1 \
     gconf2 \
+    libasound2 \
     --no-install-recommends \
     && apt-get clean \
     && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
```

**Comment by ezbik** [comment]
P.S. it also fixes audio recording.
All applies to Ubuntu.

**Comment by xorilog** [comment]
Hello @ezbik and Thank you ! I applied it to the 1.7.3 docker image, but as i do not want to replace my tag on github, it will be added in the >1.7.3 !

**Comment by rdlmda** [comment]
I had no audio (neither playback nor recording) on Telegram v2.0.1 and was able to fix it using `pulseaudio`. I'll submit a pull request, if you'd like.

**Comment by xorilog** [comment]
Hello @rdlmda, sorry for the delay, i would be happy to have it fixed if it's still broken, PR are always welcome :)

**Comment by rdlmda** [comment]
Oh no, sorry for *my* delay. I've sent a PR now.

**Comment by rdlmda** [comment]
Any issues with my pull request? I've been using it daily on my personal machine with no issues here.
